### PR TITLE
update styling and markup to remove h1 from title

### PR DESCRIPTION
**Pull request by gvonkoss**

### CODE REVIEW

**Comment by notlee** [comment]
Not should we want to target the product-name or product-tagline separately.

**Comment by gvonkoss** [comment]
But that' would involve another markup change and probably a redesign

**Comment by notlee** [comment]
I mean to maintain the class we have, which users are already including:
`<a class="o-header-services__product-name" href="#">`

**Comment by gvonkoss** [comment]
I understand that, there's just no guarantee the title will be a link or any other element, so it is inheriting directly from its parent

**Pull request merged**
